### PR TITLE
Make "postgrest" string configurable

### PR DESCRIPTION
**Pull request by framp**
The goal is to make the postgrest string completely configurable and invisible from the outside (#197)
[This PR is still a WIP]

Done:
 - `server-name` variable to replace occurrences of "postgrest"
 - `server-string` variable to replace postgres/VERSION
 - if `server-string` is undefined the default is SERVERNAME/VERSION
 - use `server-name` in the multipart boundary
 - `auth-path` variable to replace the path where users log in (eg: `/postgrest/users`)

What's missing:
 - Use a different schema for auth (instead of `postgrest`) based on the auth-path variable
 - Maybe join `server-name` and `auth-path` in a single variable?

### CODE REVIEW

**Comment by begriffs** [comment]
I'm thinking again about the security use case here. There are two things that someone may want to hide:

1. That they are using postgrest at all
2. The specific version of postgrest being run

The first one actually seems pretty hard. Even after removing the server header, changing routes, renaming the multipart separator, the server still responds in distinctive ways. For instance the specific information provided by the OPTIONS verb. I bet if anybody cared to detect if it's postgrest they could figure it out.

However the version is easier to conceal by removing the server response header. Still not totally invisible (for instance someone could post to /postgrest/tokens to check if pre-0.2.9.0).

So I'm wondering if this pull request is introducing complexity in an attempt to solve item one when it could alleviate item two by providing a flag to simply remove the server header. Might not even need to change the codebase for this. If postgrest is running behind nginx (as it might be for https support alone) then the [headers_more](http://wiki.nginx.org/HttpHeadersMoreModule) module can scrub out the header.

On the other hand, both you and @jetho submitted pull requests for overriding the server string so this seems like an important issue. Thoughts?

**Comment by jetho** [comment]
Well, I share your thoughts on this. I implemented item two because I like fine grained configuration possibilities and thought this could be useful for some people. Concerning security, one could argue that hiding/modifying the server string is somewhere in the category of "security through obscurity", because it won't protect you against application fingerprinting. In summary, I think this can be a useful configuration possibility, but I wouldn't see it as a security feature.

**Comment by framp** [comment]
I agree we're more on the configuration side and I think too it's a little
bit too convoluted at the time.

In order to simplify the PR I can probably merge auth-path and server-name
and keep server-string and server-name

**Comment by begriffs** [comment]
I'd be happy to look over the simplified version once you get a chance to update this PR.

**Comment by begriffs** [comment]
@framp hope I'm not being annoying but I wanted to check back with you about this pull request. Still interested in it? Want to push it past the finish line?

**Comment by framp** [comment]
Hey Joe,

Thanks for pinging me, and sorry for the delay.
I've just been overwhelmed with work and I don't have access to my dev
environment.
I should be able to finish up sometime before next Friday.

Cheers,
Federico

**Comment by framp** [comment]
This PR should be (finally!) ready

authPath is merged with serverName and serverName is used to pick the schema name containing auth table

**Comment by begriffs** [comment]
Thanks for making time to adjust the PR. I'll review it shortly.

**Comment by begriffs** [comment]
Actually I'm not feeling motivated by this feature right now.

**Pull request closed without merging**
