### PR TITLE
Use newer deps for GHC 8 compatibility

### LINKED ISSUE #612: GHC 8 fixes
To get postgrest building under GHC 8.0.1 for Homebrew (we only typically support the latest GHC), I've needed to add a "cabal.config" file at the root of the package containing "allow-newer: base,transformers" and patch the following three dependencies:
- bytestring-tree-builder 0.2.6
- postgresql-binary 0.9
- hasql-transaction 0.4.4.1

bytestring-tree-builder and postgresql-binary needed the GHC option "-XNoImpredicativeTypes" due to increased strictness under GHC 8.

hasql-transaction needed "base" added to its build-depends.

With these changes, postgrest builds as expected and passes CI tests.

The Homebrew Ruby code that accomplishes this is, as follows:
```
+    cabalcfg = "allow-newer: base,transformers"
+    cabalcfg << "\nconstraints:"
+    cabal_sandbox do
+      %w[
+        bytestring-tree-builder 0.2.6
+        postgresql-binary 0.9
+        hasql-transaction 0.4.4.1
+      ].each_slice(2) do |pkg, ver|
+        cabalcfg << "\n#{pkg} ==#{ver}"
+        system "cabal", "get", pkg
+        cabal_sandbox_add_source "#{pkg}-#{ver}"
+        inreplace "#{pkg}-#{ver}/#{pkg}.cabal" do |s|
+          if pkg == "hasql-transaction"
+            s.gsub! "build-depends:", "build-depends: base,"
+          else
+            s.gsub! "ghc-options:", "ghc-options: -XNoImpredicativeTypes"
+          end
+        end
+      end
+      (buildpath/"cabal.config").write(cabalcfg)
+      install_cabal_package :using => ["happy"]
+    end

```

### PR DESCRIPTION
**Pull request by begriffs**
Fixes #612 

@ilovezfs can you please check if this builds on Homebrew with GHC 8?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@begriffs Getting closer, but it's still necessary to have the "allow-newer: base,transformers" unless you patch parsers and jwt, or wai-cors (with the commit that removes the parsers dependency, so no need to patch parsers) and jwt. Here's what's needed doing wai-cors and jwt:

```
    cabal_sandbox do
      buildpath.install resource("wai-cors-remove-parsers-dep")
      system "cabal", "get", "wai-cors"
      system "/usr/bin/patch", "-p1", "-d", "wai-cors-0.2.4",
        "-i", buildpath/"3f90298038ca391351f4c2d243db3114842f4bf3.patch"
      cabal_sandbox_add_source "wai-cors-0.2.4"

      system "cabal", "get", "jwt"
      inreplace "jwt-0.7.1/jwt.cabal",
        "build-depends:       base >= 4.6 && < 4.9",
        "build-depends:       base >= 4.6 && < 5"
      cabal_sandbox_add_source "jwt-0.7.1"

      install_cabal_package :using => ["happy"]
```
The relevant commits are
https://github.com/larskuhtz/wai-cors/commit/3f90298038ca391351f4c2d243db3114842f4bf3
and
https://bitbucket.org/ssaasen/haskell-jwt/commits/2c48f81ed5d53af4d5d3ecf49f6e45adae61b348?at=master

**Comment by ilovezfs** [comment]
@begriffs FYI https://github.com/Homebrew/homebrew-core/pull/1587

**Comment by begriffs** [comment]
@ilovezfs this branch now builds locally for me with GHC 8.0.1. It's having trouble on CI though building helper tools.

I'm curious about your initial motivation to make this build on GHC 8. Is it required nowadays in order to release postgrest on Homebrew? I'd like to make a new release and I'm wondering if this PR will need to be merged before that can happen.

**Comment by ilovezfs** [comment]
Yes, as I mentioned here https://github.com/begriffs/postgrest/issues/612#issue-157042696, we typically only support the latest version of GHC. So before upgrading GHC in homebrew/core I went through and made sure each formula either built out of the box with GHC 8 or could be patched to do so. Right now the only exception that has been made is for Idris: https://github.com/Homebrew/homebrew-core/commit/a93d454017c2d04236ce52d06613fa85c19198b0

Am I reading that correctly that hackage-security is the one that's breaking first?

**Comment by begriffs** [comment]
That's right. Hackage-security is not technically required for postgrest itself but for `cabal-install` which I install on CI to check that regular (non-Stack) cabal can find a build plan for the program.

**Comment by ilovezfs** [comment]
I just tried building hackage-security here and it built fine in a cabal sandbox, so I think it's a conflict in that stack configuration.

**Comment by ilovezfs** [comment]
```
==> cabal sandbox init
Config file path source is default config file.
Config file
/private/tmp/hackage-security-20160605-96479-17byccf/hackage-security-0.5.1.0/.cabal/config
not found.
Writing default configuration to
/private/tmp/hackage-security-20160605-96479-17byccf/hackage-security-0.5.1.0/.cabal/config
Writing a default package environment file to
/private/tmp/hackage-security-20160605-96479-17byccf/hackage-security-0.5.1.0/cabal.sandbox.config
Creating a new sandbox at
/private/tmp/hackage-security-20160605-96479-17byccf/hackage-security-0.5.1.0/.cabal-sandbox
==> cabal update
Downloading the latest package list from hackage.haskell.org
==> cabal install --jobs=64 --max-backjumps=100000 --only-dependencies
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/lib'
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries'
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/hackage-security-20160605-96479-17byccf/hackage-security-0.5.1.0/.cabal-sandbox
Downloading base16-bytestring-0.1.1.6...
Downloading base64-bytestring-1.0.0.1...
Downloading cryptohash-sha256-0.11.100.0...
Configuring base16-bytestring-0.1.1.6...
Configuring base64-bytestring-1.0.0.1...
Downloading ed25519-0.0.5.0...
Configuring cryptohash-sha256-0.11.100.0...
Downloading mtl-2.2.1...
Downloading network-2.6.2.1...
Configuring ed25519-0.0.5.0...
Configuring mtl-2.2.1...
Downloading tar-0.5.0.3...
Downloading text-1.2.2.1...
Configuring network-2.6.2.1...
Downloading zlib-0.6.1.1...
Configuring tar-0.5.0.3...
Building base16-bytestring-0.1.1.6...
Building base64-bytestring-1.0.0.1...
Configuring text-1.2.2.1...
Configuring zlib-0.6.1.1...
Building cryptohash-sha256-0.11.100.0...
Building ed25519-0.0.5.0...
Building mtl-2.2.1...
Building tar-0.5.0.3...
Building text-1.2.2.1...
Building zlib-0.6.1.1...
Installed base16-bytestring-0.1.1.6
Installed cryptohash-sha256-0.11.100.0
Installed base64-bytestring-1.0.0.1
Installed mtl-2.2.1
Installed ed25519-0.0.5.0
Building network-2.6.2.1...
Installed zlib-0.6.1.1
Installed tar-0.5.0.3
Installed network-2.6.2.1
Installed text-1.2.2.1
Downloading parsec-3.1.11...
Configuring parsec-3.1.11...
Building parsec-3.1.11...
Installed parsec-3.1.11
Downloading network-uri-2.6.1.0...
Configuring network-uri-2.6.1.0...
Building network-uri-2.6.1.0...
Installed network-uri-2.6.1.0
==> cabal install --jobs=64 --max-backjumps=100000 --prefix=/usr/local/Cellar/hackage-security/0.5.1.0
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/lib'
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries'
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/hackage-security-20160605-96479-17byccf/hackage-security-0.5.1.0/.cabal-sandbox
Configuring hackage-security-0.5.1.0...
Building hackage-security-0.5.1.0...
Installed hackage-security-0.5.1.0
Error: Empty installation
```

**Comment by ilovezfs** [comment]
For what it's worth, this is how we build cabal-install:
```
class CabalInstall < Formula
  desc "Command-line interface for Cabal and Hackage"
  homepage "https://www.haskell.org/cabal/"
  url "https://hackage.haskell.org/package/cabal-install-1.24.0.0/cabal-install-1.24.0.0.tar.gz"
  sha256 "d840ecfd0a95a96e956b57fb2f3e9c81d9fc160e1fd0ea350b0d37d169d9e87e"
  revision 1

  bottle do
    cellar :any_skip_relocation
    sha256 "8a7c7e1b9603df8770455d9cda8b98018591e8218971a2a73928aba122586ba7" => :el_capitan
    sha256 "5eec25c84652f5516e369f338945ea5a7807ae509680a752bf39c0c379374b40" => :yosemite
    sha256 "065cd05eeb2f0b5a1cde05c12dd3835af5bca08f5dea0beef6b63fcaeb330cce" => :mavericks
  end

  depends_on "ghc"

  fails_with :clang if MacOS.version <= :lion # Same as ghc.rb

  # disables haddock for hackage-security
  patch :p2 do
    url "https://github.com/haskell/cabal/commit/9441fe.patch"
    sha256 "5506d46507f38c72270efc4bb301a85799a7710804e033eaef7434668a012c5e"
  end

  def install
    system "sh", "bootstrap.sh", "--sandbox"
    bin.install ".cabal-sandbox/bin/cabal"
    bash_completion.install "bash-completion/cabal"
  end

  test do
    system "#{bin}/cabal", "--config-file=#{testpath}/config", "info", "cabal"
  end
end
```

**Comment by ilovezfs** [comment]
Yeah, I'm not seeing any issue building those packages: https://gist.github.com/ilovezfs/427f6855c459a026404a8a1115589103

I'll see if I can reproduce the issue with stack.

**Comment by ilovezfs** [comment]
Yeah, no problem building it with stack either: https://gist.github.com/ilovezfs/770826a53bfd5fd1e4e20601671d2908

But that's with

iMac-TMP:~ joe$ stack --version
Version 1.1.2 x86_64 hpack-0.14.0

So I bet you're right that it's just the older version of stack acting up.

**Comment by begriffs** [comment]
OK it builds with newer binutils. It was just `ld` freaking out.

Everything looks good except this check: `stack exec --no-ghc-package-path -- cabal install --only-d --dry-run`. This is because I've given Stack a hint of which commit to use when building wai-cors, but cabal sees only what's on hackage. Once wai-cors bumps its version and updates hackage then this should pass. Hope that happens soon.

**Comment by ilovezfs** [comment]
You could patch wai-cors for that as I'm already doing: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgrest.rb#L52-L57

**Comment by begriffs** [comment]
If @larskuhtz can bump the version of wai-cors in the next few days then I'd rather wait for that instead of doing the patching which seems like added complexity. It's good to know how to do it though, thanks for showing me.

**Comment by larskuhtz** [comment]
Oh, almost forgot about that. I am going to release a new version of wai-Cors today. Thanks for reminding me.

**Comment by begriffs** [comment]
@larskuhtz I see you updated your repo and tagged the new version -- thanks! Could you push the new version to hackage too please?

**Comment by larskuhtz** [comment]
Version 0.2.5 of wai-cors is now on hackage. Building the test-suite (with --enable-tests) may required passing `--allow-newer=transformers`, due to an upper bound on simple-sendfile.

**Comment by ilovezfs** [comment]
Nice. Also looks like https://hackage.haskell.org/package/jwt pushed 0.7.2, so no need to patch that either.

@larskuhtz have you pestered simple-sendfile upstream about this yet?

**Comment by larskuhtz** [comment]
no, since only the test-suites of wai-cors depend on it.

**Comment by ilovezfs** [comment]
@begriffs I'm pretty that if you re-trigger CI, it will pass now :)

**Comment by ilovezfs** [comment]
@begriffs FYI https://github.com/Homebrew/homebrew-core/pull/1776/files

Passes with flying colors :)

**Comment by ilovezfs** [comment]
Woo hoo :green_apple:

**Comment by begriffs** [comment]
Nice! Now that we know it builds with GHC 8 I'm going to tell Stack to use an LTS release again. The newest one is LTS-6.2 which is GHC 7.10.3, so I'll use that. Regular cabal builds like homebrew does will not be affected and can use GHC 8 if they want.

**Comment by ilovezfs** [comment]
Hurray https://github.com/Homebrew/homebrew-core/pull/1892

**Pull request merged**
