### PR TITLE
Refactored circle.yml

### PR DESCRIPTION
**Pull request by jhr007**
Added docker-compose.yml and Dockerfile.development
Updated Dockerfile

### CODE REVIEW

**Comment by begriffs** [comment]
Looking forward to getting this merged and all set up!

If you don't mind I'd like to get v0.4 released prior to merging though. There are a number of changes and moving parts in progress so it'll be simplest to make sure all that stuff goes well before introducing another complication.

It'll give us a little time to review this pull request as well.

**Comment by jhr007** [comment]
I added my Docker Hub email/user/pass as env variables in CircleCI's web interface.. see scripts/docker_push.sh for specific vars. 

Adding user/pass brings up the security concern if auto building pull requests is enabled. I could change the circle.yml to write the env variables to the artifact folder, and voila secrets are public and permanent(contact circleci support to remove).  

In circle.yml there are two deploys to docker_hub, one for master and one for v1.1.1 like tags.

`make_docker_release.sh` builds the PostgREST docker image for both master branch and v1.1.1 tags. 

``` yaml
#circle.yml
deployment:
  dockerhub_latest:
    branch: master
    commands:
      - scripts/make_docker_release.sh
      - scripts/docker_push.sh

  dockerhub_version:
    tag: /^v[0-9]+(\.[0-9]+)*/
    #owner doesn't like env vars...
    owner: begriffs
    commands:
      - scripts/make_docker_release.sh
      - scripts/docker_push.sh
```

**Comment by jhr007** [comment]
The s3 release could be added to the CI as well. 
https://circleci.com/docs/continuous-deployment-with-amazon-s3/

**Comment by deinspanjer** [comment]
@jhr007 If you get a chance, take a look at PR #762 and let me know if you see any problems with it.
Even if we use that method to do the actual docker build, there are still some important pieces of your PR here that we could still use such as the Docker tagging and pushing.  I wasn't sure what exactly the circle.yaml bit was about with the generating of a tar image and such, so I don't know where that plays in.

**Comment by jhr007** [comment]
@deinspanjer That tar is using [circle's caching](https://circleci.com/docs/how-cache-works/) to save/load a giant(GBs) docker image between builds. This cache is persistent between builds, so the image theoretically doesn't have to be recreated from scratch each build.  In this PR `~/.docker` isn't being cached.

I originally ran with the idea that having a docker dev image to do the building would provide a developer image for present/future PostgREST devs and maybe help builds. 

However, the builds turned out to be slower. Note the build times at https://circleci.com/gh/jhr007/postgrest/tree/master, the latest ~5 min builds on master are building outside of a docker image. 

Although thinking about it a little more... these times might not be realistic. Commits to postgrest/master are probably less frequent than updates to cabal repos/packages. I.e. Each postgrest/master build will always have to pull newer cabal packages.

**Comment by begriffs** [comment]
I'm looking into the DbStructure PRs and then Docker and then this one. Haven't forgotten it!

**Comment by begriffs** [comment]
Can I get your opinion about #808?

**Comment by begriffs** [comment]
I'm going to close this as it is getting out of date with the current state of these files. Many of the changes took inspiration from this PR however.

Sorry for the tumultuous way we've been trying to make Docker work, and the slow response to your contribution here.

**Pull request closed without merging**
