### PR TITLE
Add ability to order by jsonb keys, fix #644

### LINKED ISSUE #644: Can not order by keys in jsonb
Say we have a USERS table and in USERS we have `json_data` jsonb column to store detail info.
The problem I confront is that I can't order result by keys in `json_data`.

Actual cases:
`http://localhost:3000/users?order=json_data->>created_at::date.asc`
`http://localhost:3000/users?order=json_data->>created_at::date.desc`

Both return incorrect results (Neither asc nor desc)

### PR DESCRIPTION
**Pull request by steve-chavez**
Fixes #644. If all is ok I can help with adding this change to the docs.

### CODE REVIEW

**Comment by ruslantalpa** [comment]
Looks good.
Let's first merge my open PR before this one because this one is shorter and might not need fixing the conflicts.

**Comment by begriffs** [comment]
@steve-chavez you're on 🔥 ! Thanks for another great PR, I'll attend to it after getting Ruslan's reviewed and merged.

**Comment by begriffs** [comment]
This branch is ready for a rebase (luckily looks like a simple conflict in the changelog), then ready to merge.

**Comment by begriffs** [comment]
Nevermind, I fixed the conflict manually.

**Pull request merged**
