### PR TITLE
Test and fixes for #407 #403 #107

### PR DESCRIPTION
**Pull request by ruslantalpa**
This PR adds tests for a weak authenticator #407, and ads a check for detecting relations #403
A good side effect is it fixes also an old issue #107 (test passing, it can be closed).

One thing i noticed is that test got a lot slower from 20s to 90s.
The only major thing that changed is that we rely on CTE instead of information_schema and the new queries take about 500ms to execute. Since the queries in the dbstructure are executed only once in the beginning i don't think it will impact runtime performance however i think that these queries are somehow rerun at each test. 
Can anyone spot why this is happening and maybe fix it in a separate PR?

### CODE REVIEW

**Comment by diogob** [comment]
@ruslantalpa during the tests it seems that the DbStructure gets recreated for each test case.
The problem is here: https://github.com/begriffs/postgrest/blob/master/test/SpecHelper.hs#L58
The withApp is called in ```around``` for each case.

**Comment by ruslantalpa** [comment]
Thought so, anyway, this does not impact the runtime so i think that can be fixed with another PR

**Comment by begriffs** [comment]
(from a conversation in the chat room)

I'd rather get the tests fast again before merging. It may take a little while to figure out how to do it and during that time people branching off master would have to deal with slow tests. 

One technique to make it faster would be to make `withApp` accept a `DbStructure` argument so it wouldn't have to run `getDbStructure` inside. However it's unclear how to get that value from Main.hs into each of the specs. We use hspec-discover to find and run each spec. [This article](https://stackoverflow.com/questions/30631737/hspec-discovery-custom-main-and-passing-argument-to-spec) makes it seem like we can't get an extra argument into the spec that way. We could ditch hspec-discover and call the tests manually from Main and pass them the db structure to give to withApp.

Another technique could be to not call withApp so often. It gets called for every spec item. Maybe it could be put into a `beforeAll` or something. We would have to change the signature of the function somehow.

**Comment by begriffs** [comment]
As mentioned in the chatroom, I pushed a patch to make the tests fast on branch spec-cache-dbstructure. One test is failing there due to the changes but the whole suite runs in three seconds.

**Comment by diogob** [comment]
roadrunner

**Comment by ruslantalpa** [comment]
Closing this one since the changes in here are included in #421

**Pull request closed without merging**
