### PR TITLE
Remove versioning support

### PR DESCRIPTION
**Pull request by calebmer**
Changes discussed in #304. This probably warrants some more discussion before merging.

### CODE REVIEW

**Comment by diogob** [comment]
:+1: 
But I think it's wise to keep the readme section about versioning and just mention to the use of different instances on different schemas + nginx.

**Comment by begriffs** [comment]
...and so begins the first breaking change for v0.3! I created a [v3](https://github.com/begriffs/postgrest/tree/v3) branch for these kind of changes, could you close this PR and open a new one against that branch? That will be the branch for big new auth changes as well. This way master will stay free to proceed with bug fixes and little additions and the v3 will contain the crazy new stuff.

**Comment by calebmer** [comment]
@diogob good idea

@begriffs Cool, I just have two questions first. How do you want to handle the changelog for v3 changes? And second (this is for everyone), I can also replace all of the `"1"` schema references in the tests to `public` or `test`, would you like that too? I didn't do it initially for the fear of the “who moved my cheese” reaction :relaxed:

**Comment by begriffs** [comment]
I'd say just add your changes to the changelog as usual. When we eventually merge v3 into master then we'll combine the entries in the changelog from both branches together.

And sure you can change the schema for the tests. There may be some merge work later if people add more tests on master but it will be straightforward.

**Pull request closed without merging**
