### PR TITLE
Added Put request for postgrest/users endpoint

### PR DESCRIPTION
**Pull request by ireverent**
Added Put to postgrest/user enpoint. Uses similar code to put requests elseware. Should be able to add a new resource as well as update a resource.

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for rebasing and fixing it up.

It makes me wonder, what if we allow `version=postgrest` in the accept header to switch into the postgrest schema. Then our normal code could do the work to support all the operations on the users table. The database admin could forbid read access on this table to the anonymous role so random people wouldn't be able to get a list of the users and hashed passwords. Do you think this could work?

**Comment by ireverent** [comment]
Actually that might be a really good idea. Some of my team have been trying to figure out how we might be able to integrate into other Postgres based databases (PostGIS, Arcgis) when we don't control the schema or schema name but do control the roles.

**Comment by ireverent** [comment]
With the header switch, do we want to be able to pass in on the postgrest script an enum of all the valid schema? That way we can open it up to existing schemas without having to open up all schemas if we don't want to.

**Comment by begriffs** [comment]
Maybe we don't have to open the postgrest schema. We can use that trick about creating a view of the full auth table that restricts people to seeing roles which they have permission to switch into.

We could add a command line option which will scaffold the auth stuff so that it's easy to get started.

**Comment by begriffs** [comment]
I'm going to close this PR for now. I think we'll be making more comprehensive changes to auth.

**Comment by ireverent** [comment]
Np. Keep me up on it and let me know if there is anything I can do to help.

**Pull request closed without merging**
