### PR TITLE
Apply range headers to rpc

### PR DESCRIPTION
**Pull request by diogob**
I believe this adds consistency for a very small cost.
Using the same mechanism to paginate the result of procedure calls makes it easier to reuse front end pagination code.

### CODE REVIEW

**Comment by begriffs** [comment]
This will be really convenient for the client, and it didn't take much code either.

What do you think about adding a response range header as well? It would create more parity between tables and rpc if the rpc response included a `Content-Range`. See the tests in [RangeSpec.hs](https://github.com/begriffs/postgrest/blob/f3d4d1fb60edce96abfe9b39c38222278a67e9b4/test/Feature/RangeSpec.hs) for examples.

**Comment by diogob** [comment]
Oh sure, forgot about that! Will add tonight ;)

**Comment by diogob** [comment]
I believe it's ready for merging :D

**Comment by diogob** [comment]
@begriffs I just rebased after #503 
Should be good to merge again ;)

**Comment by begriffs** [comment]
Great stuff!

**Pull request merged**
