### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by steve-chavez**

### CODE REVIEW

**Comment by begriffs** [comment]
So now I push a new tag and the auto-release process will kick in?

**Comment by steve-chavez** [comment]
Yes, the tag should do it.

**Comment by steve-chavez** [comment]
Travis somehow not building on pushed commit to master https://travis-ci.org/begriffs/postgrest/builds.

**Comment by begriffs** [comment]
I triggered a manual build just to see what happens - https://travis-ci.org/begriffs/postgrest/builds/272557816

**Pull request merged**
