### PR TITLE
Run GC every 2s rather than 0.3s

### LINKED ISSUE #565: Strange increase in CPU-usage over time
We have a server running on Debian with PostgreSQL 9.5 and latest (I think) postgrest.

The server is more or less just idling since it is a production server not yet in production.

Over time I have seen that the cpu-usage is increasing. After some weeks it is using more than 50 % of 400 % in total (4 cores). I can see on the graphs that the usage is increasing very slowly day by day. 

I have 2 instances of postgrest runing on the server.

I see the same thing on our test server, but that one is under some load during this test phase. But also when it is idling it uses a lot of CPU.

When I restart the postgrest instances things go back to normal.

### PR DESCRIPTION
**Pull request by begriffs**
Fixes #565

### CODE REVIEW

**Comment by begriffs** [comment]
Looks like cabal check is confusing the RTS option with a ghc-option:

```
stack exec -- cabal check
The following warnings are likely affect your build negatively:
* Instead of 'ghc-options: -I2"' use 'include-dirs: 2"'

Hackage would reject this package.
```

Or maybe grouped quoted options is not valid in a cabal file. I'll consult the docs...

**Comment by begriffs** [comment]
This builds and passes `cabal check`. Looking at its eventlog the GC doesn't run much as I use the program. Although going back to the original rtsopts the GC didn't seem to run much either.

Also if I change it to `"-with-rtsopts=-N -K8"` it will not crash the program whereas running with `+RTS -K8 -RTS` will. So I'm not sure it's actually using this configuration.

**Comment by begriffs** [comment]
Turns out I had to run `stack clean` for the rtsopts to take effect in a new build. Merging.

**Comment by eric-brechemier** [comment]
> Turns out I had to run `stack clean` for the rtsopts to take effect in a new build. Merging.

Is it required for those of us building PostgREST from source?

**Comment by ruslantalpa** [comment]
my guess is yes

**Comment by begriffs** [comment]
To pick up changed GHC flags it's better to clean to be on the safe side.

**Pull request merged**
