### PR TITLE
Per-route content negotiation, and OpenAPI only for root

### PR DESCRIPTION
**Pull request by begriffs**
This is a backward-incompatible change for 0.4. Requesting `/` used to return the API schema using a custom JSON format, or return an OpenAPI description depending on Accept headers. This PR removes support for the non-OpenAPI response. We still have a custom response for the OPTIONS verb on specific tables.

This also allows each route to customize content negotiation for the Content-Types it supports. It will properly reject Accept headers that are unsatisfiable.

Two concerns about the changes:
* I removed a test for authorization which checks that the schema includes only the tables that the currently authenticated user can see. The OpenAPI equivalent should be added.
* It strips charset encoding from Accept headers and uses UTF-8 for responses. This might not be correct HTTP semantics. For instance if a client said `Accept: application/json; charset=ISO-8859-1` we would not reply with HTTP 415 (Unsupported media type) but instead would succeed with `Content-Type: application/json; charset=UTF-8`.

### CODE REVIEW

**Comment by ruslantalpa** [comment]
i would say remove `options` for each table. there is not much value in it if the openapi describes all routes and all tables and fields/columns

**Comment by begriffs** [comment]
I removed the API description from OPTIONS responses, but kept the handlers there to deal with CORS requests. Unfortunately we've lost test coverage of foreign key stuff, and the test that users with less db permissions are unable to see tables they cannot access.

**Comment by ruslantalpa** [comment]
This part https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Types.hs#L134-L163 is also probably not needed anymore but you are right about those tests, they are needed.
Any way to add a completely new type of tests to does not go through `warp` code but just tests the output of functions like `dbColumns`?

**Comment by begriffs** [comment]
Closes #56
Closes #144

**Comment by begriffs** [comment]
@ruslantalpa could you help with adding tests for the relations in another PR?

**Comment by begriffs** [comment]
I'm going to merge this. Let's think of how we might add more test coverage for relations.

**Pull request merged**
