### PR TITLE
Update hjsonschema package

### PR DESCRIPTION
**Pull request by PierreR**

### CODE REVIEW

**Comment by PierreR** [comment]
I was expecting circleCI to start testing this ... ?

**Comment by PierreR** [comment]
I don't know how to fix the failing test ...

Any idea ?

**Comment by begriffs** [comment]
I was trying to restart the build on Circle to see if it the failure is intermittent. However the build is happening under your username rather than mine for some reason. Could you push another commit to try it again? Or even `git commit --amend` and tweak the final commit so git sees it as changed.

**Comment by PierreR** [comment]
Link info to a similar reverted attempt: https://github.com/begriffs/postgrest/pull/836/commits/fb676011e545b50065f4d52a5d07e800fdaad885

**Comment by PierreR** [comment]
I will redo that PR going more slowly  by first removing `hsonpointer` see #1004

**Pull request closed without merging**
