### PR TITLE
Faster queries using json_agg

### PR DESCRIPTION
**Pull request by ruslantalpa**
with these changes a single postgrest joined query with json encoding over 3 tables is as fast as making 3 distinct queries (with `id in (...)` condition) on one table each.

tests changed because json_agg returns a slightly different json format, but the same data.

### CODE REVIEW

**Comment by begriffs** [comment]
Nice, I know you've been wanting to fix this one for a while.

My only note is that `json_agg` is broken on Citus, but then again so are other things postgrest uses, so we won't really be much worse off for future compatibility.

Also, when you say this returns a slightly different json format, do you mean it simply re-orders the rows?

**Comment by ruslantalpa** [comment]
i mean new lines between array items

**Comment by begriffs** [comment]
OK, no big deal then. Guessing that testing `[json|…|]` for equality disregards whitespace differences and hence the reason for that change in the tests.

**Comment by ruslantalpa** [comment]
yes, exactly

**Comment by begriffs** [comment]
This looks good to merge!

**Pull request merged**
