### PR TITLE
Upgrade hasql-transaction

### PR DESCRIPTION
**Pull request by begriffs**

### CODE REVIEW

**Comment by begriffs** [comment]
@hudayou I'm noticing that the test "returns a valid openapi spec" takes a very long time on CI. We should look into it...

**Comment by hudayou** [comment]
@bergriffs Got you, going to look into it.

**Comment by hudayou** [comment]
@begriffs Have you looked at this [Drone over Circle] (http://bitemyapp.com/posts/2016-03-28-speeding-up-builds.html)?

If somebody can donate a build machine, it would be great.

Tried to run all the tests locally, it cost only 5 seconds. Seems to be an IO problem on Circle,
I guess they are not using SSDs?

Anyway, still trying to see if there are any work arounds for Circle.

I did some benchmark locally, here is the result.
	Mon Jun 27 14:18 2016 Time and Allocation Profiling Report  (Final)

	   spec +RTS -N -sstderr -p -RTS

	total time  =        5.00 secs   (4997 ticks @ 1000 us, 1 processor)
	total alloc = 5,401,960,168 bytes  (excludes profiling overheads)

COST CENTRE             MODULE                        %time %alloc

toJSON.mapMaybe         Data.JsonSchema.Draft4.Schema  37.8   56.6
internalSchemaHashMap   Data.JsonSchema.Draft4.Schema  30.0   13.8
internalSchemaHashMap.f Data.JsonSchema.Draft4.Schema   6.9    5.7
parseJSON.\             Data.JsonSchema.Draft4.Schema   5.7    5.0
toJSON                  Data.JsonSchema.Draft4.Schema   1.3    0.3
parseJSON.checkUnique   Data.Validator.Draft4.Any       1.2    4.5
parseJSON               Data.Validator.Utils            1.0    2.0
parseJSON               Data.Validator.Draft4.Any       0.9    3.1
parseJSON.checkUnique   Data.Validator.Draft4.Object    0.7    1.0
parseJSON               Data.JsonSchema.Draft4.Schema   0.6    1.2

**Comment by hudayou** [comment]
@begriffs Also the validation of JSON schema seems requiring a lot of CPU, while the testing is running, the CPU usage goes up to 110%.

**Pull request merged**
