### PR TITLE
Added support for Nulls First / Nulls Last

### PR DESCRIPTION
**Pull request by jcristovao**
So, this adds support for an optional ```nullsfirst``` or ```nullslast``` (verbose, I know, but it keeps in line with postgres terminology) parameter to the order parameters. 

So, we can have:

```GET /people?order=age.desc.nullsfirst,height.asc.nullslast```

This is grouped with the previous PR, but as soon as you accept it I can make the necessary adjustments to this one.

I can also add tests, of course, I just would like to know which table should I use... can I add a nullable field to items?

Hope you find this useful, 
Cheers

PS: I am also thinking about adding a ```isnull``` / ```isnotnull``` to the Filters, seems good?

### CODE REVIEW

**Comment by begriffs** [comment]
This looks great! Just add some tests and I think it's good to merge. The `no_pk` table would work well for tests. It has two string columns `a` and `b`, either of which can be null.

**Comment by begriffs** [comment]
If you're too busy right now to add tests and update the docs I can take care of it. Let me know.

**Comment by jcristovao** [comment]
Hi, sorry, had a rather busy past week.
I'll try to add them this monday, I'll let you know then how it goes :)

Thanks

**Comment by jcristovao** [comment]
Ok, added some tests, add to do some refactoring, please let me know if you are ok with it
Thanks!

**Comment by begriffs** [comment]
Cool, thanks for the tests. Could you also rebase these commits against the new stuff on master? It no longer merges cleanly. I'd like to get this change into the next minor release which I'll be making soon.

**Comment by begriffs** [comment]
I rebased this and merged to master. Thanks for the feature!

**Pull request closed without merging**
