### PR TITLE
Get CSV response

### PR DESCRIPTION
**Pull request by diogob**
This is a draft, for I still need to make the accept headers work with text/csv + the API versioning.
But I'd like to get some early feedback on the code so far :D
This should fix issue #226

### CODE REVIEW

**Comment by diogob** [comment]
BTW, the build is failing because of some problem with a hasql package during ```cabal exec packdeps``` step, but I haven't changed anything regarding the packages.

**Comment by begriffs** [comment]
This will be a nice feature!

As for the test failure, try changing the version constraint in the cabal file to

```
hasql-postgres == 0.10.4.*
```

I should make packdeps a warning rather than an error because it breaks unpredictably when people update other packages.

**Comment by begriffs** [comment]
I bumped the hasql-postgres version on master so when we merge this branch the packdeps will not complain.

Just tried out your feature and it's working great (nice refactors inside too)! Only thing I noticed is that the response headers say `Content-Type: application/json` even when it's returning csv in the body. Once that is fixed we should be good to merge.

**Comment by diogob** [comment]
Thanks man, I should be able to finish it in the next couple of days.

**Comment by jwarlander** [comment]
Really looking forward to this, let me know if I can help with any testing!

I'm looking at potentially using this for a data API that might at times be returning millions of rows, thus we're trying to avoid JSON.

**Comment by diogob** [comment]
@begriffs sorry, I was still working out some issues here, I'm opening a new PR for that ;)

**Comment by diogob** [comment]
And thanks for the neat mention in the README :D

**Pull request merged**
