### PR TITLE
Improved usage/error message when required args missing

### LINKED ISSUE #130: Usage message on error gives no hint about what's wrong
I'm giving `postgrest` what look like reasonable options, but it won't start and gives me no hints about why.

    > postgrest-0.2.5.1 --db-name mydb_dev --db-user mydbuser --db-pass mypassword --db-host localhost --port 8082 --db-port 5432 --db-pool 100
    Usage: postgrest (-d|--db-name ARG) [-P|--db-port ARG] (-U|--db-user ARG)
                     [--db-pass ARG] [-h|--db-host ARG] [-p|--port ARG]
                     (-a|--anonymous ARG) [-s|--secure] [--db-pool ARG]
      create a REST API to an existing Postgres database

Do the options need to be in a specific order? Does one of them have an invalid value? I tried using the long options just in case, and adding `--db-pool` and `--db-port` even when I'm fine with defaults.

I don't know what my particular problem might be, but the app could give me some help. For extra confusion, sometimes it prints the vertical explanation of each option, and sometimes it doesn't.

[EDIT: Looks like `--anonymous` is required.]

### PR DESCRIPTION
**Pull request by adambaker**
fixes #130

Not quite finished. Needs to handle errors on parsing int options without throwing read exceptions.

### CODE REVIEW

**Comment by PierreR** [comment]
Out of curiosity why moving away from `optparse` ? Is there something clumsy about it with regards to dealing with missing args ?
I am asking because I have been using `optparse` exclusively and I have had the feeling that getting this kind of errors right might be the biggest challenge ... That said I really like the `parsing` aspect of it but dealing with errors that cross parsers hasn't been that easy.

**Comment by adambaker** [comment]
I wanted to leave `optparse-applicative` because I couldn't find good documentation for it. In contrast, the system getopt is small, well documented, with examples I can follow to get a sense of how I might attack more complicated options parsing. @PierreR

**Comment by begriffs** [comment]
I merged this and then decided to revert master. The `record` dependency is kind of disastrous right now. It breaks hlint and requires some functionality that appears to require a newer version of `base` than exists on circle ci. However trying to rebuild on circle with force-reinstalled deps cannot complete in under the build time limit of 20 minutes.

I think until `record` matures we need to rework this with more classical haskell records.

**Comment by adambaker** [comment]
Huh? Why does it build on CI just fine on the loop/recur fork then.

**Comment by begriffs** [comment]
After more investigation things look a little more hopeful.

* The hlint failure is being addressed right now in https://github.com/haskell-suite/haskell-src-exts/pull/208
* You did have your branch building but I was unable to make my own copy of it build within the circle time limit. Perhaps your branch's cabal cache was built up more gradually from previous commits introducing new packages gradually. I'll ask circle for their opinion on the build failure we get with the default build configuration.

For the moment I'm going to focus on the other pull requests to give the above items more time to resolve themselves.

**Comment by PierreR** [comment]
If I understand this correctly, this could be fixed really easily (and elegantly) with `optparse`. It is just a matter of using a Maybe type for the optional parameter.

You can look [here](
https://github.com/bartavelle/language-puppet/blob/master/progs/PuppetResources.hs) for an example.

I would really think twice before replacing `optparse`. It is quite flexible and neat. It is also the most popular library for this kind of stuff.

I would understand replacing it if there was a good reason to do so but the documentation one you mention seems a bit weak. The documentation is not perfect but it is not bad (just my opinion).

**Comment by begriffs** [comment]
I agree that it's better to use a common library like optparse rather than implementing a homemade thing. However it's also true that this use case of giving customized error messages for missing arguments is a known deficiency for optparse as noted in the haskell.org [option parsing wiki](https://wiki.haskell.org/Command_line_option_parsers):

> "for wrong arguments it does not show a specific error message but the general usage pattern"

I think you're right that the current option documentation isn't that bad so we'll stick with optparse for now. Adam's parser does provide a better user experience with customized hints about missing options, but the negatives outweigh the positives for ditching optparse.

**Pull request merged**
