### PR TITLE
Fix options on non existant tables, closes #442

### LINKED ISSUE #442: OPTIONS request to non-existent table does not throw any error
Feel free to close this if it's intentional, but I noticed that an `OPTIONS` request to a [non-existent table](https://postgrest.herokuapp.com/foo) does not give any indication that it doesn't exist. It returns `200` with a body that looks like an empty table:
```json
{
  "pkey": [],
  "columns": []
}
```

### PR DESCRIPTION
**Pull request by calebmer**

### CODE REVIEW

**Comment by diogob** [comment]
LGTM :smiley:

**Comment by begriffs** [comment]
Sorry I just merged hasql-19 and it makes this branch not merge cleanly. Can you rebase please?

**Comment by begriffs** [comment]
I rebased this and merged manually. Thank you for the fix!

**Comment by calebmer** [comment]
Sorry for not rebasing. I haven't had a lot of time to develop recently 😐

**Comment by begriffs** [comment]
No problem at all, it went smoothly.

**Pull request closed without merging**
