### PR TITLE
Remove range check

### PR DESCRIPTION
**Pull request by calebmer**
Forgot to throw this suggestion in from @ruslantalpa into #375.

### CODE REVIEW

**Comment by begriffs** [comment]
Is there a feature test that illustrates what this does?

**Comment by calebmer** [comment]
This isn't a feature, just a small nuance (which should technically never matter) in how the code works. To quote @ruslantalpa:

> Just remembered, override is necessary because if the range specifies limit > 1 then asJsonSingleF will fail

The override referred to is this change.

**Comment by begriffs** [comment]
I'm assuming we could construct a request with a range that would cause a response failure, but which would work once this PR is merged.

**Comment by ruslantalpa** [comment]
Exactly, sending prefer singular and range 10 will generate a bad query/response

**Comment by begriffs** [comment]
I wrote this test which passes on master (post refactor PR merge).

```haskell
    it "works in the presence of a range header" $
      let headers = ("Prefer","plurality=singular") :
            (rangeHdrs $ ByteRangeFromTo 0 9) in
      request methodGet "/items" headers ""
        `shouldRespondWith` ResponseMatcher {
          matchBody    = Just [json| {"id":1} |]
        , matchStatus  = 200
        , matchHeaders = []
        }
```
Does this mean we're good?

**Comment by ruslantalpa** [comment]
so you say without merging this, the test passes?
My concern was this line
https://github.com/begriffs/postgrest/blob/master/src/PostgREST/QueryBuilder.hs#L297
Not sure why the test passes though ...

**Comment by begriffs** [comment]
Yeah it passes on master just as master is. Did I screw up the test somehow? Try pulling master and adding the test locally.

**Pull request closed without merging**
