### PR TITLE
The correct HTTP status code for integrity constraint violation is 509, fixes #469

### LINKED ISSUE #469: Wrong status code returned for POST on duplicate key violating unique constraint
I stumbled upon this response coming from the latest Postgrest.
```js
Status 400 
{"hint":null,"details":"Key (eid, uid)=(e1, 42d94270-1fe6-457c-8dd0-152eec8ac8f4) already exists.","code":"23505","message":"duplicate key value violates unique constraint \"event_feedbacks_sid_uid_key\""}
```
400 means bad request, but the request was perfectly ok (I just inserted the row one minute ago with the an identical request). 
In my opinion, the best code would be 409 Conflict: "The request could not be completed due to a conflict with the current state of the resource."

### PR DESCRIPTION
**Pull request by sscarduzio**

### CODE REVIEW

**Comment by calebmer** [comment]
Just make sure to also fix the [failing test](https://github.com/begriffs/postgrest/blob/master/test/Feature/InsertSpec.hs#L77) 👍

**Comment by begriffs** [comment]
Thanks for the fix! Can you please add a test of inserting a duplicate and seeing the error code?

**Comment by sscarduzio** [comment]
is there anything else I can do for this?

**Comment by begriffs** [comment]
Beautiful, thanks.

**Pull request merged**
