### PR TITLE
order does not work

### PR DESCRIPTION
**Pull request by jcristovao**
I'm a bit baffled nobody noticed this before :P

Anyhow, without it order does not work.

Thanks,
Cheers

### CODE REVIEW

**Comment by begriffs** [comment]
Wow that's crazy. Thanks for the patch! Can you create a regression test for this as well?

**Comment by begriffs** [comment]
There must be something wrong with these tests: https://github.com/begriffs/postgrest/blob/master/test/Feature/QuerySpec.hs#L26-L40

**Comment by jcristovao** [comment]
Well, the test use:
```get "/items?id=lte.2&order=asc.id```

The documentation uses:
```GET /people?order=age.desc,height.asc```

Shall we keep inline with the documentation?

**Comment by begriffs** [comment]
Oh I see, the tests don't match the docs. I like the docs' way better so this PR looks good other than the broken test. For some reason Circle CI did not run the tests on the PR. Let me look into that first, try to enable automatic pull request tests, then get this merged.

**Comment by begriffs** [comment]
OK I think I got Circle CI to start paying attention to pull requests from forks. Can you modify the order tests and add another commit to the PR? We'll see if Circle kicks in.

**Comment by jcristovao** [comment]
Done, sorry for the delay :)

**Comment by begriffs** [comment]
Great stuff, thanks again.

(I'll merge this but wait to bump the package version until I merge in another change relating to improved command line argument handling.)

**Comment by jcristovao** [comment]
Ok, thanks!
Any chance you'll also consider the other pull requests?
Cheers

**Comment by begriffs** [comment]
Yep, planning to get to them all today.

**Pull request merged**
