### PR TITLE
Protolude completion in library and executable

### PR DESCRIPTION
**Pull request by diogob**
This gets #695 very close to completion.
Items left open:
 * Conversion of test suite to protolude (should be much easier than library)
 * Clean up of `Unsafe` module being used in DbStructure 
 * Create custom Prelude on top of Protolude

### CODE REVIEW

**Comment by begriffs** [comment]
Thank you so much, it's great to get it all standardized!

Do you mind if I merge #634, then #693 then this one? You'll have to do a little rebasing but I think it will be easier than rebasing the other way around.

**Comment by diogob** [comment]
Sure, let's get these two merged since they have been in queue for a while.
I'll rebase as soon as this is done ;)

**Comment by begriffs** [comment]
OK, all clear for rebase! 🏁

**Comment by diogob** [comment]
Nice and easy :D

**Pull request merged**
