### PR TITLE
Changes stack resolver to nightly.

### PR DESCRIPTION
**Pull request by diogob**
This removes the need to use hspec in extra-deps and I believe it fits our development pace better :D

### CODE REVIEW

**Comment by begriffs** [comment]
I was wondering why hspec was in extra deps...

We could also set the resolver to `nightly` without a date after it to allow it to keep advancing every day.

**Comment by ruslantalpa** [comment]
Pls no, each day it would take 20 min to do the first build

**Comment by ruslantalpa** [comment]
Do that only before release day

**Comment by begriffs** [comment]
@ruslantalpa it's usually fast actually because it copies binaries from older Stack "sandboxes" when it can. So most the time it says "Copying foo-1.2.3..." and occasionally builds a package when it was actually updated. It does take more disk space though probably.

**Comment by begriffs** [comment]
@diogob made the point that even if we could do this it is better to pin to a specific nightly for predictable builds and move the version forward as needed.

**Comment by diogob** [comment]
I'm leaving now, but I'll fix the linter messages later on ;)

**Pull request merged**
