### PR TITLE
Make postgrest a library

### PR DESCRIPTION
**Pull request by srid**
Still working on this. I'm seeing many errors like:

```
src/PostgREST/Types.hs:41:44:
    Not in scope: type constructor or class ‘SqlValue’

src/PostgREST/Types.hs:46:28:
    Not in scope: type constructor or class ‘SqlValue’
```

No clue how to fix them as I'm not a Haskell expert.

### CODE REVIEW

**Comment by begriffs** [comment]
Hey thanks for starting this restructuring. Turns out that `src/PostgREST/Types.hs` is no longer needed. The SqlValue stuff was from HDBC. Probably it hasn't been required by other modules for a while.

A working version of your work is on the branch https://github.com/begriffs/postgrest/tree/srid-makelibrary
Give it a try and see if it exports the things you need.

**Comment by srid** [comment]
Cool, everything works now. I tested using a fresh cabal sandbox and `cabal build exe:postgrest` successfully generates the executable under `dist/build/PostgREST/postgrest`.

@begriffs - the PR is now ready. If you could merge and cut a release to hackage, I would appreciate it, as this means I can start extending postgrest without having to maintain a fork!

**Comment by begriffs** [comment]
I'm working on the JWT pull request right now. Planning to merge that and then we can rebase this on top. Sound good? I'm thinking it might be an easier rebase than the other way around.

**Comment by srid** [comment]
Sure!

**Comment by framp** [comment]
I'm wondering, what's the point of moving files in the PostgREST directory?
Why not just change `Other-Modules` to `Exposed-Modules`?

Also I don't think I'm able to grasp the benefits of exposing all the modules.
Maybe `App` could be useful, so that some other Haskell application could use it as a wai middleware in another application.

What are you using it for @srid?

**Comment by srid** [comment]
Exposing just `App` may be enough, however without namespacing it (`PostgREST.App`) it could conflict with other packages.

Basicaly I want to modify `Main.hs` and add a bunch of features (custom auth, serve static files, --db-uri) but without having to maintain a fork. So it makes sense to use postgrest as a library (not executable).

I'll look into resolving merge conflicts next.

**Comment by srid** [comment]
@begriffs rebased and ready to merge! :-)

With jwt support, perhaps it is time to up the version to 0.3?

**Comment by begriffs** [comment]
Cool, can you squash them into one commit please?

I was planning on releasing as 0.2.9.0 since JWT is an addition rather than a backward-incompatible change. Now you could argue that renaming modules is backward-incompatible, but since we're only exposing the modules for the first time I think it's additive which qualifies as a minor version.

**Comment by srid** [comment]
> Cool, can you squash them into one commit please?

done.

**Comment by begriffs** [comment]
I'll make the release to hackage and build the new binaries. Glad you found a way to work with the original code rather than maintain a fork.

**Comment by begriffs** [comment]
I released 0.2.9.0 but Hackage will not accept it:

```
Error: Invalid package

'ghc-options: -Wall -Werror' makes the package very easy to break with future
GHC versions because new GHC versions often add new warnings. Use just
'ghc-options: -Wall' instead. If you want to use this, make it conditional
based on a flag (with 'manual: True' and 'default: False') and enable that
flag during development.
```

I'll remove -Werror from the cabal file but I want to find a way to have Circle override it and build with Werror anyway. I'll also add `cabal check` to the Circle steps.

**Comment by spl** [comment]
I'm not sure if this is useful, but there was a recent Well-Typed post that mentioned [using `cabal` with `-Werror` behind a flag](http://www.well-typed.com/blog/2015/05/recent-hackage-improvements/).

**Comment by begriffs** [comment]
@spl thanks for that. Got past the problem using the flag trick.

Version 0.2.9.1 is now up on hackage.

**Pull request merged**
