### PR TITLE
Support of is / is not null | true | false | unknown

### PR DESCRIPTION
**Pull request by jcristovao**
This adds support for the constructs ```is null```, ```is not null``` and similars (```true```, ```false``` and ```unkwnon```).
These values are not verified neither escaped. Should they be? I am not really familiar with the procedure in this case, so I could use some help here.

This patch, however, does not support the form ```expression IS DISTINCT FROM expression```.

[Source](http://www.postgresql.org/docs/9.4/static/functions-comparison.html)

Thanks

### CODE REVIEW

**Comment by begriffs** [comment]
Alternately if you like the API better we could let people say `/foo?col=is.null` and `/foo?col=is.true` and make sure that the value being interpolated matches a whitelist of safe options (null, true, false, etc) before interpolating it.

**Comment by begriffs** [comment]
(also sorry it took me a while to respond to your pull request, I do appreciate your work)

**Comment by jcristovao** [comment]
Actually, my particular use case just requires ```null``` and ```notnull```, I've added the other ones more for completeness. Any of the APIs you suggested looks great to me... I've implemented the simplistic approach (white listing), but please feel free to implement a better approach!

And no problem on the delay... now it was my turn to take some time ;)

Cheers

**Comment by begriffs** [comment]
K, it's all rebased tested and merged.

**Pull request closed without merging**
